# Generated by Django 4.1.7 on 2023-03-11 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0004_alter_customer_options_customer_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('itemCount', models.PositiveIntegerField(default=0, verbose_name='Item Count')),
                ('description', models.CharField(max_length=5000, verbose_name='Description')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerOrders', to='customer.customer')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
