# Generated by Django 4.1.7 on 2023-03-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=200, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=200, verbose_name='Last Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('currencyBalance', models.FloatField(default=0, verbose_name='Currency Balance')),
                ('pageVisits', models.IntegerField(default=0, verbose_name='Page Visits')),
            ],
        ),
    ]
