# Generated by Django 4.1.7 on 2023-03-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='question_text',
        ),
    ]
