# Generated by Django 4.1.7 on 2023-03-06 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pageVisits',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Page Visits'),
        ),
    ]
